---
name: Throuh Time and Space
author: AIVA
music_file: through_time_and_space.mp3
sheets:
    easy:
        2: easy.qtap2
        3: easy.qtap3
    hard:
        2: hard.qtap2
        3: hard.qtap3
bpm: 105
cover: cover.webp
